package nl.kbresearch.europeana_newspapers.NerAnnotator.output;

import nl.kbresearch.europeana_newspapers.NerAnnotator.TextElementsExtractor;

import org.w3c.dom.Document;


/**
 * Output handler for the result of the NER process on a single ALTO document
 * 
 * @author rene
 * 
 */
public interface ResultHandler {
    /**
     * Called at the beginning of the document
     */
    void startDocument();

    /**
     * Called at the beginning of each ALTO textblock
     */
    void startTextBlock();

    /**
     * called at the end of a line
     * 
     * @param hyphenated
     *            true, if there is a hyphen at the end
     */
    void newLine(boolean hyphenated);

    /**
     * Called for each token generated by the {@link TextElementsExtractor}
     * after NER processing. This does not include the spaces between the
     * elements.
     * 
     * @param wordid
     *            the reference to the ALTO element.
     * @param originalContent
     *            the uncleaned content of the word. Useful to reconstruct the
     *            original input.
     * @param word
     *            the input used for NER processing. This might include content
     *            from the Element described by continuationid
     * @param label
     *            the label given by the NER processing. Null, if no label was
     *            attached.
     * @param continuationid
     *            if not null, the element referenced by this is the second part
     *            of the same "word".
     */
    void addToken(String wordid, String originalContent, String word, String label, String continuationid);

    /**
     * Called at the end of a text block
     */
    void stopTextBlock();

    /**
     * Called at the end of the document
     */
    void stopDocument();

    /**
     * This is called in any case after the processing of the file.
     */
    void close();
    
    /**
     * 
     */
    void globalShutdown();

    /**
     * @param doc
     */
    void setAltoDocument(Document doc);
}
